name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file backend/Dockerfile --tag retrobyte-be:$(date +%s)
      run: docker build . --file frontend/Dockerfile --tag retrobyte-fe:$(date +%s)
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag the Docker image
      run: docker tag retrobyte-be:$(date +%s) mig1881/retrobyte-be:$(date +%s)
      run: docker tag retrobyte-fe:$(date +%s) mig1881/retrobyte-fe:$(date +%s)

    - name: Push the Docker image to Docker Hub
      run: docker push mig1881/retrobyte-be:$(date +%s)
      run: docker push mig1881/retrobyte-fe:$(date +%s)

